# Site Settings
title:               it.dev.claudio
tagline:             yet another developer blog
description:
baseurl:            #"/Lagrange"
url:                #"https://klaus82.github.io/"
github:
  url:               #"https://github.com/klaus82"
author:
  name:              "Claudio Masolo"
  email:             "claudio.masolo@gmail.com"
  twitter:           "ClaudioAkaKlaus"
  instagram:         ""
  github:            "klaus82"
  facebook:          ""
  linkedin:          ""

navigation:
- title: About me
  url: /about
#- title: Writing
#  url: /writing
#- title: Contact
#  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
